# Overall parameters
dt: 0.01

# Motor model parameters
R : 0.7
L: 0.00272
kt: 1.16e-6
kv: 78.54
kl: 6.4e-5
J_motor: 0.000028
v_max: 14.8


# Main system
J_body: 0.01
turrets:
  - [-0.3,  0.2]
  - [ 0.3,  0.2]
  - [-0.3, -0.2]
  - [ 0.3, -0.2]
