#ifndef MAPLE_AUTOGEN_ROSPO_COM_FORCE_IN_UB_PARAMS_HPP__
#define MAPLE_AUTOGEN_ROSPO_COM_FORCE_IN_UB_PARAMS_HPP__

#define dF__max 5
#define delta__max 3

#endif // MAPLE_AUTOGEN_ROSPO_COM_FORCE_IN_UB_PARAMS_HPP__
