#ifndef MAPLE_AUTOGEN_ROSPO_COM_FORCE_MAX_PARAMS_HPP__
#define MAPLE_AUTOGEN_ROSPO_COM_FORCE_MAX_PARAMS_HPP__

#define Uvc_max 25
#define TUvc_max 3

#endif // MAPLE_AUTOGEN_ROSPO_COM_FORCE_MAX_PARAMS_HPP__
